name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup needed tools
      run: |
        apt-get update
        apt-get install -y make gcc clang
    - name: make
      run: make
  
